# requirements.yml

# you can download roles using:
#
# ansible-galaxy install -p roles -r requirements.yml

roles:
  - name: geerlingguy.postgresql
    version: 3.5.2
  - name: geerlingguy.php
    version: 4.8.0
  - name: geerlingguy.apache
    version: 3.0.3
